# Set up the environment.
language: node_js
node_js:
  - 12.18.0

# Use a popular, small linux distro.
dist: trusty

# List of services needed.
services:
  - mongodb

addons:
  chrome: stable

# List of environment variables.
env:
  - NODE_ENV=ci

# Speeds up the building process.
cache:
  directories:
    - node_modules
    - client/node_modules

# Install and build scripts.
install:
  - npm install
  - npm run build

script:
  - nohup npm run start &
  # Wait for the server to start.
  - sleep 30
  - npm run test:ci

# Add a decryption step for .env.enc => .env file.
before_install:
  - openssl aes-256-cbc -K $encrypted_f47fc5ed2408_key -iv $encrypted_f47fc5ed2408_iv -in .env.ci.enc -out .env -d
